ci: add release-please
com-pas/compas-core pull request #277
Opened 2023-11-15 22:40 UTC by juancho0202

2023-11-20 15:02 UTC, pascalwilbrink requested changes

2023-11-20 15:02 UTC, pascalwilbrink commented on .github/workflows/release-please.yml
> +          release-type: node
```suggestion
          release-type: maven
```

2023-11-24 15:39 UTC, samirromdhani commented on .github/workflows/release-please.yml
> +        run: ./mvnw -B -s custom_maven_settings.xml -Prelease clean deplo
```suggestion
        run: ./mvnw -B -s custom_maven_settings.xml -Prelease clean deploy
```

2023-11-28 10:43 UTC, pascalwilbrink approved these changes

2023-11-28 11:54 UTC, merged